# Generated by Django 3.1.4 on 2021-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoouser',
            name='wants_email_notifications',
            field=models.BooleanField(default=False, verbose_name='Receive notifications via email'),
        ),
    ]
