# Generated by Django 3.1.4 on 2021-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_auth', '0004_delete_zoousernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoouser',
            name='wants_email_notifications',
        ),
        migrations.AddField(
            model_name='zoouser',
            name='notification_method',
            field=models.CharField(choices=[('NONE', 'None'), ('APP', 'Bell icon'), ('EMAIL', 'E-mail'), ('A&E', 'Both')], default='APP', max_length=5, verbose_name='Notification Method'),
        ),
    ]
