# Generated by Django 3.1.4 on 2021-06-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_auth', '0005_auto_20210519_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
