# Generated by Django 3.1.4 on 2021-04-17 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('closed_date', models.DateTimeField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('B', 'Bug'), ('F', 'Feature Request'), ('I', 'Improvement Request'), ('M', 'Maintenance')], max_length=2)),
                ('priority', models.IntegerField(choices=[(0, 'Trivial'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('action', models.CharField(choices=[('W', 'Awaiting assignment'), ('A', 'In Analysis'), ('D', 'In Development'), ('C', 'Completed'), ('R', 'Rejected')], max_length=2)),
                ('assignee', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket_system.ticket')),
            ],
        ),
    ]
