# Generated by Django 3.1.4 on 2021-04-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0003_auto_20210418_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='action',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('A', 'In Analysis'), ('D', 'In Development'), ('CA', 'Cancelled'), ('R', 'Rejected'), ('CO', 'Completed')], default='U', max_length=2),
        ),
    ]
