# Generated by Django 3.1.4 on 2021-04-20 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0005_auto_20210419_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='watched_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
