# Generated by Django 3.1.4 on 2021-04-22 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0006_ticket_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Last Updater'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(choices=[('ZV', 'Zooverse'), ('LD', "Lion's Den")], max_length=2, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Trivial'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('A', 'In Analysis'), ('D', 'In Development'), ('CA', 'Cancelled'), ('R', 'Rejected'), ('CO', 'Completed')], default='U', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('B', 'Bug'), ('F', 'Feature Request'), ('I', 'Improvement Request'), ('M', 'Maintenance')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, default=None, related_name='watched_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
