# Generated by Django 3.1.4 on 2021-05-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0009_auto_20210514_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaction',
            name='type',
            field=models.CharField(choices=[('CREATE', 'created'), ('EDIT', 'edited'), ('DELETE', 'deleted')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ticketchange',
            name='new_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketchange',
            name='old_value',
            field=models.TextField(blank=True),
        ),
    ]
