# Generated by Django 3.1.4 on 2021-05-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0010_auto_20210515_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchange',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketchange',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
