# Generated by Django 3.1.4 on 2021-05-15 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0013_userticketnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTicketNotification',
            new_name='TicketActionNotification',
        ),
    ]
